services:
  # Backend API service
  - type: web
    name: todo-app-api
    env: node
    region: oregon # or your preferred region
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

  # Frontend web service
  - type: web
    name: todo-app-frontend
    env: static
    region: oregon # or your preferred region
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://todo-app-api.onrender.com # Update this with your actual backend URL

databases:
  - name: todo-db
    region: oregon # or your preferred region
    plan: free # or other plan
